services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: harmony_reader_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   volumes:
  #     - .:/rails
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
volumes:
  postgres_volume:
