inherit_from: .rubocop_todo.yml
inherit_gem:
  syntax_tree: config/rubocop.yml
  relaxed-rubocop: .rubocop.yml
AllCops:
  NewCops: enable
  Exclude:
    - .git/**/*
    - vendor/**/*
    - bin/**/*
Bundler/OrderedGems:
  Enabled: false
